export const actions={
    FETCH_DATA_FROM_FIRESTORE : "FETCH_DATA_FROM_FIRESTORE",
    SET_DATA_FROM_CLIENT : "SET_DATA_FROM_CLIENT",
    ADD_NEW_PAYMENT_MODE : "ADD_NEW_PAYMENT_MODE",
    SET_CURR_PAYMENT_OPTION:"SET_CURR_PAYMENT_OPTION"
}