export const actions = {
    SET_STEP_INDEX:'SET_STEP_INDEX',
    NAVIGATE_STEPS:'NAVIGATE_STEPS',
    SET_BILLING_ADDRESS:'SET_BILLING_ADDRESS',
    SET_DELIVERY_ADDRESS:'SET_DELIVEY_ADDRESS',
    SET_PAYMENT_OPTION:'SET_PAYMENT_OPTION'
}