export const actions = {
    LOGIN_REQUEST : "LOGIN_REQUEST",
    SIGNUP_REQUEST : "SIGNUP_REQUEST",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAILED:"LOGIN_FAILED",
    SIGNUP_SUCCESS:"SIGNUP_SUCCESS",
    SIGNUP_FAILED:"SIGNUP_FAILED",
}